### ISSUE TITLE
add how to update data in the readme

### ISSUE THREAD

**Issue by chaserx** [openlexington/whats_my_district_redux#6]
how to get geojson from gov shapfiles

**Comment by chaserx** [comment]
next extension to this would be how to automate the geojson creation

**Comment by chaserx** [comment]
@blakeshall could you add some knowledge here, please?

**Comment by blakeshall** [comment]
All i did was use this: http://ogre.adc4gis.com/ Which uses ogr2ogr\* so I imagine it could be easily automated. If you have some way of knowing when the data has been updated then just fire off a script that uses ogr2ogr to convert from shape to geojson. The main concerns are filenames so the that the js doesn't get wonky.
- http://www.gdal.org/ogr2ogr.html

**Comment by chaserx** [comment]
Thanks, @blakeshall 

Looks like @benbalter has a nice write up on this too. http://ben.balter.com/2013/06/26/how-to-convert-shapefiles-to-geojson-for-use-on-github/

**Comment by blakeshall** [comment]
Are there any sort of notifications for when datasets are updated?

**Comment by chaserx** [comment]
Ummm. I'm not sure.... maybe not with this version of CKAN.
